version: '3.5'

services:
  tararest:
    build:
      context:
        .
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_MAX_RPS: "5"
    ports:
      - "8089:8080"
    volumes:
      - "tararest-app-data:/var/lib/tarantool"

volumes:
  tararest-app-data:
