---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by al-kov.
--- DateTime: 25.11.2019 05:01
---

local handlers = require("app.rest.handlers")
local middleware = require("app.rest.middleware")

local router = require('http.router').new()
router:route({ path = '/kv/:id', method = 'GET' }, handlers.kv.get)
router:route({ path = '/kv/:id', method = 'PUT' }, handlers.kv.put)
router:route({ path = '/kv', method = 'POST' }, handlers.kv.post)
router:route({ path = '/kv/:id', method = 'DELETE' }, handlers.kv.delete)

router:use(middleware.catch_error, { name = 'catch_error' })

return {
    router = router
}
