---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by al-kov.
--- DateTime: 25.11.2019 04:51
---

local tsgi = require('http.tsgi')
local response = require('http.router.response')
local json = require('json')
local log = require('log')

local function limit_rps(env)
    --local data = box.space.counter.index.primary:select(key_id)[1]

    resp = tsgi.next(env)
    return resp
end

local function catch_error(env)
    local resp = setmetatable({ headers = {} }, response.metatable)
    local function try()
        resp = tsgi.next(env)
    end
    local res, exception = pcall(try)
    if not res then
        local json_data = { error = string.format('%s', exception) }
        resp.headers['content-type'] = "application/json; charset=utf-8"
        resp.body = json.encode(json_data)
        resp.status = 400
    end
    log.info('Response: %s', resp.body)
    return resp
end

local middleware = {
    catch_error = catch_error,
    limit_rps = limit_rps,
}

return middleware
