#!/usr/bin/env tarantool
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alkov.
--- DateTime: 22.11.2019 17:00
---

local log = require('log')
local cfg = require('app.config')
local schema = require('app.schema')
local rest = require('app.rest')
local httpd = require('http.server')

log.info('Starting App...')

box.cfg {}
schema.init()

local server = httpd.new(cfg.host, cfg.port, {
    log_requests = true,
    log_errors = true
})

server:set_router(rest.router)

server:start()
