---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by al-kov.
--- DateTime: 25.11.2019 05:01
---

local kv_handlers = require("app.rest.handlers.kv")

return {
    kv = kv_handlers
}
